name: Build and Release WPF App

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore
        working-directory: VAC

      - name: Build Solution
        run: dotnet build --configuration Release --no-restore
        working-directory: VAC

      - name: Publish Application
        run: dotnet publish -c Release -o output
        working-directory: VAC

      - name: Create ZIP Archive
        run: Compress-Archive -Path VAC/output/* -DestinationPath release.zip

      - name: Get Latest Commit Message (PowerShell)
        id: commit_message
        run: |
          $commit_message = git log -n 1 --pretty=%B
          Write-Host "Commit message: $commit_message"
          $tag_name = "v1.0.$($commit_message -replace ' ', '_')"  # Replace spaces with underscores
          echo "TAG_NAME=$tag_name" >> $env:GITHUB_ENV

      - name: Configure Git User
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Create and Push Git Tag
        run: |
          git tag $env:TAG_NAME
          git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git $env:TAG_NAME
        env:
          TAG_NAME: ${{ env.TAG_NAME }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME }}
          files: release.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
